# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a7995528f0a2ee112e1874713383bd74c83b05d422489b15780649898285cdee8f07eba0d258926e01263d69565e7ecf0c338e2cae133250570386ac2a6ff497

test:
  secret_key_base: b45864ca190cf78fca8e5142047bb70e1871d78ab53f9f9409b5e7ca5acd780b51b593353c42b37c8d73d4b881d5de00f1fe54831cab51507a73bbdaf87a5ebb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
